add_item:
  fields:
    name:
      required: true
      example: Beer
      selector:
        text:

remove_item:
  fields:
    name:
      required: true
      example: Beer
      selector:
        text:

complete_item:
  fields:
    name:
      required: true
      example: Beer
      selector:
        text:

incomplete_item:
  fields:
    name:
      example: Beer
      required: true
      selector:
        text:

complete_all:
incomplete_all:
clear_completed_items:
sort:
  fields:
    reverse:
      default: false
      selector:
        boolean:

sort_by_date:
  fields:
    reverse:
      default: false
      selector:
        boolean:
export:
  fields:
    filetype:
      required: false
      default: json
      example: json
      selector:
        select:
          options:
            - label: JSON
              value: json
            - label: CSV
              value: csv
            - label: PDF
              value: pdf
